apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-edu-slave-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /share_8c0fade2_649f_4ca5_aeaa_8fd57904f8d5/jenkins/edu_slave
    server: 172.25.1.162
  persistentVolumeReclaimPolicy: Retain
