apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-edu-slave-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: jenkins-edu-slave-pv
